name: film_magic
description: "iPF developer quiz interview"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  get_it: ^8.0.3
  dart_mappable: ^4.5.0
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  gap: ^3.0.1
  flex_color_scheme: ^8.2.0
  path_provider: ^2.1.5
  firebase_core: ^3.14.0
  flutter_dotenv: ^5.2.1
  internet_connection_checker: ^3.0.1
  go_router: ^15.2.4
  spider: ^4.2.2
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.2.0
  build_runner: ^2.4.8
  mockito: ^5.4.5
  build_test: ^3.2.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
